### model
model_name_or_path: /home/jd/model/Qwen3-VL-30B-A3B-Instruct
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: false
freeze_multi_modal_projector: false
flash_attn: fa2
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: new_fvqa_agent_sft,palace_agent_sft,webqa_agent_sft,livevqa_agent_sft,wikiart_agent_sft,wiki_zh_agent_sft,wiki_en_agent_sft
dataset_dir: /home/jd/OpenSearch-VL-main/SFT/data
template: qwen3_vl
cutoff_len: 32000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/qwen3_vl_30b_a3b/full/sft_agent
logging_steps: 5
save_steps: 200
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none
save_total_limit: 10

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
gradient_checkpointing: true
learning_rate: 2.0e-5
num_train_epochs: 8.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
eval_strategy: "no"
